grails-app/domain/commissions/Broker.groovy
package commissions

class Broker extends Person {

    static constraints = {
    }
}

grails-app/controllers/commissions/BrokerController.groovy
package commissions



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BrokerController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Broker.list(params), model:[brokerInstanceCount: Broker.count()]
    }

    def show(Broker brokerInstance) {
        respond brokerInstance
    }

    def create() {
        respond new Broker(params)
    }

    @Transactional
    def save(Broker brokerInstance) {
        if (brokerInstance == null) {
            notFound()
            return
        }

        if (brokerInstance.hasErrors()) {
            respond brokerInstance.errors, view:'create'
            return
        }

        brokerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'broker.label', default: 'Broker'), brokerInstance.id])
                redirect brokerInstance
            }
            '*' { respond brokerInstance, [status: CREATED] }
        }
    }

    def edit(Broker brokerInstance) {
        respond brokerInstance
    }

    @Transactional
    def update(Broker brokerInstance) {
        if (brokerInstance == null) {
            notFound()
            return
        }

        if (brokerInstance.hasErrors()) {
            respond brokerInstance.errors, view:'edit'
            return
        }

        brokerInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Broker.label', default: 'Broker'), brokerInstance.id])
                redirect brokerInstance
            }
            '*'{ respond brokerInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Broker brokerInstance) {

        if (brokerInstance == null) {
            notFound()
            return
        }

        brokerInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Broker.label', default: 'Broker'), brokerInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'broker.label', default: 'Broker'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/broker/_form.gsp
<%@ page import="commissions.Broker" %>



<div class="fieldcontain ${hasErrors(bean: brokerInstance, field: 'addresses', 'error')} ">
	<label for="addresses">
		<g:message code="broker.addresses.label" default="Addresses" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${brokerInstance?.addresses?}" var="a">
    <li><g:link controller="geographicalLocator" action="show" id="${a.id}">${a?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="geographicalLocator" action="create" params="['broker.id': brokerInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'geographicalLocator.label', default: 'GeographicalLocator')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: brokerInstance, field: 'birthDate', 'error')} required">
	<label for="birthDate">
		<g:message code="broker.birthDate.label" default="Birth Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="birthDate" precision="day"  value="${brokerInstance?.birthDate}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: brokerInstance, field: 'firstName', 'error')} required">
	<label for="firstName">
		<g:message code="broker.firstName.label" default="First Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="firstName" required="" value="${brokerInstance?.firstName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: brokerInstance, field: 'gender', 'error')} required">
	<label for="gender">
		<g:message code="broker.gender.label" default="Gender" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="gender" from="${commissions.Gender?.values()}" keys="${commissions.Gender.values()*.name()}" required="" value="${brokerInstance?.gender?.name()}" />

</div>

<div class="fieldcontain ${hasErrors(bean: brokerInstance, field: 'lastName', 'error')} required">
	<label for="lastName">
		<g:message code="broker.lastName.label" default="Last Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="lastName" required="" value="${brokerInstance?.lastName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: brokerInstance, field: 'middleName', 'error')} required">
	<label for="middleName">
		<g:message code="broker.middleName.label" default="Middle Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="middleName" required="" value="${brokerInstance?.middleName}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: brokerInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="broker.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${brokerInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: brokerInstance, field: 'type', 'error')} required">
	<label for="type">
		<g:message code="broker.type.label" default="Type" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="type" from="${commissions.PartyType?.values()}" keys="${commissions.PartyType.values()*.name()}" required="" value="${brokerInstance?.type?.name()}" />

</div>

grails-app/views/broker/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'broker.label', default: 'Broker')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-broker" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-broker" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${brokerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${brokerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:brokerInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/broker/edit.gsp
<%@ page import="commissions.Broker" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'broker.label', default: 'Broker')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-broker" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-broker" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${brokerInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${brokerInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:brokerInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${brokerInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/broker/index.gsp
<%@ page import="commissions.Broker" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'broker.label', default: 'Broker')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-broker" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-broker" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="birthDate" title="${message(code: 'broker.birthDate.label', default: 'Birth Date')}" />
					
						<g:sortableColumn property="firstName" title="${message(code: 'broker.firstName.label', default: 'First Name')}" />
					
						<g:sortableColumn property="gender" title="${message(code: 'broker.gender.label', default: 'Gender')}" />
					
						<g:sortableColumn property="lastName" title="${message(code: 'broker.lastName.label', default: 'Last Name')}" />
					
						<g:sortableColumn property="middleName" title="${message(code: 'broker.middleName.label', default: 'Middle Name')}" />
					
						<g:sortableColumn property="name" title="${message(code: 'broker.name.label', default: 'Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${brokerInstanceList}" status="i" var="brokerInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${brokerInstance.id}">${fieldValue(bean: brokerInstance, field: "birthDate")}</g:link></td>
					
						<td>${fieldValue(bean: brokerInstance, field: "firstName")}</td>
					
						<td>${fieldValue(bean: brokerInstance, field: "gender")}</td>
					
						<td>${fieldValue(bean: brokerInstance, field: "lastName")}</td>
					
						<td>${fieldValue(bean: brokerInstance, field: "middleName")}</td>
					
						<td>${fieldValue(bean: brokerInstance, field: "name")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${brokerInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/broker/show.gsp
<%@ page import="commissions.Broker" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'broker.label', default: 'Broker')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-broker" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-broker" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list broker">
			
				<g:if test="${brokerInstance?.addresses}">
				<li class="fieldcontain">
					<span id="addresses-label" class="property-label"><g:message code="broker.addresses.label" default="Addresses" /></span>
					
						<g:each in="${brokerInstance.addresses}" var="a">
						<span class="property-value" aria-labelledby="addresses-label"><g:link controller="geographicalLocator" action="show" id="${a.id}">${a?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
				<g:if test="${brokerInstance?.birthDate}">
				<li class="fieldcontain">
					<span id="birthDate-label" class="property-label"><g:message code="broker.birthDate.label" default="Birth Date" /></span>
					
						<span class="property-value" aria-labelledby="birthDate-label"><g:formatDate date="${brokerInstance?.birthDate}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${brokerInstance?.firstName}">
				<li class="fieldcontain">
					<span id="firstName-label" class="property-label"><g:message code="broker.firstName.label" default="First Name" /></span>
					
						<span class="property-value" aria-labelledby="firstName-label"><g:fieldValue bean="${brokerInstance}" field="firstName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${brokerInstance?.gender}">
				<li class="fieldcontain">
					<span id="gender-label" class="property-label"><g:message code="broker.gender.label" default="Gender" /></span>
					
						<span class="property-value" aria-labelledby="gender-label"><g:fieldValue bean="${brokerInstance}" field="gender"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${brokerInstance?.lastName}">
				<li class="fieldcontain">
					<span id="lastName-label" class="property-label"><g:message code="broker.lastName.label" default="Last Name" /></span>
					
						<span class="property-value" aria-labelledby="lastName-label"><g:fieldValue bean="${brokerInstance}" field="lastName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${brokerInstance?.middleName}">
				<li class="fieldcontain">
					<span id="middleName-label" class="property-label"><g:message code="broker.middleName.label" default="Middle Name" /></span>
					
						<span class="property-value" aria-labelledby="middleName-label"><g:fieldValue bean="${brokerInstance}" field="middleName"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${brokerInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="broker.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${brokerInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${brokerInstance?.type}">
				<li class="fieldcontain">
					<span id="type-label" class="property-label"><g:message code="broker.type.label" default="Type" /></span>
					
						<span class="property-value" aria-labelledby="type-label"><g:fieldValue bean="${brokerInstance}" field="type"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:brokerInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${brokerInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>