grails-app/domain/commissions/GeographicalLocator.groovy
package commissions

class GeographicalLocator {

    String line1;
    String line2;
    String city;
    String county;
    String state;
    String zipcode;
    Country country;

    static belongsTo = [party: Party]

    static constraints = {
        country(blank : false)
    }
}

grails-app/controllers/commissions/GeographicalLocatorController.groovy
package commissions


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class GeographicalLocatorController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond GeographicalLocator.list(params), model: [geographicalLocatorInstanceCount: GeographicalLocator.count()]
    }

    def show(GeographicalLocator geographicalLocatorInstance) {
        respond geographicalLocatorInstance
    }

    def create() {
        respond new GeographicalLocator(params)
    }

    @Transactional
    def save(GeographicalLocator geographicalLocatorInstance) {
        if (geographicalLocatorInstance == null) {
            notFound()
            return
        }

        if (geographicalLocatorInstance.hasErrors()) {
            respond geographicalLocatorInstance.errors, view: 'create'
            return
        }

        geographicalLocatorInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'geographicalLocator.label', default: 'GeographicalLocator'), geographicalLocatorInstance.id])
                redirect geographicalLocatorInstance
            }
            '*' { respond geographicalLocatorInstance, [status: CREATED] }
        }
    }

    def edit(GeographicalLocator geographicalLocatorInstance) {
        respond geographicalLocatorInstance
    }

    @Transactional
    def update(GeographicalLocator geographicalLocatorInstance) {
        if (geographicalLocatorInstance == null) {
            notFound()
            return
        }

        if (geographicalLocatorInstance.hasErrors()) {
            respond geographicalLocatorInstance.errors, view: 'edit'
            return
        }

        geographicalLocatorInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'GeographicalLocator.label', default: 'GeographicalLocator'), geographicalLocatorInstance.id])
                redirect geographicalLocatorInstance
            }
            '*' { respond geographicalLocatorInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(GeographicalLocator geographicalLocatorInstance) {

        if (geographicalLocatorInstance == null) {
            notFound()
            return
        }

        geographicalLocatorInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'GeographicalLocator.label', default: 'GeographicalLocator'), geographicalLocatorInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'geographicalLocator.label', default: 'GeographicalLocator'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/geographicalLocator/_form.gsp
<%@ page import="commissions.GeographicalLocator" %>



<div class="fieldcontain ${hasErrors(bean: geographicalLocatorInstance, field: 'country', 'error')} required">
	<label for="country">
		<g:message code="geographicalLocator.country.label" default="Country" />
		<span class="required-indicator">*</span>
	</label>
	<g:select name="country" from="${commissions.Country?.values()}" keys="${commissions.Country.values()*.name()}" required="" value="${geographicalLocatorInstance?.country?.name()}" />

</div>

<div class="fieldcontain ${hasErrors(bean: geographicalLocatorInstance, field: 'city', 'error')} required">
	<label for="city">
		<g:message code="geographicalLocator.city.label" default="City" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="city" required="" value="${geographicalLocatorInstance?.city}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: geographicalLocatorInstance, field: 'county', 'error')} required">
	<label for="county">
		<g:message code="geographicalLocator.county.label" default="County" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="county" required="" value="${geographicalLocatorInstance?.county}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: geographicalLocatorInstance, field: 'line1', 'error')} required">
	<label for="line1">
		<g:message code="geographicalLocator.line1.label" default="Line1" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="line1" required="" value="${geographicalLocatorInstance?.line1}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: geographicalLocatorInstance, field: 'line2', 'error')} required">
	<label for="line2">
		<g:message code="geographicalLocator.line2.label" default="Line2" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="line2" required="" value="${geographicalLocatorInstance?.line2}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: geographicalLocatorInstance, field: 'party', 'error')} required">
	<label for="party">
		<g:message code="geographicalLocator.party.label" default="Party" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="party" name="party.id" from="${commissions.Party.list()}" optionKey="id" required="" value="${geographicalLocatorInstance?.party?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: geographicalLocatorInstance, field: 'state', 'error')} required">
	<label for="state">
		<g:message code="geographicalLocator.state.label" default="State" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="state" required="" value="${geographicalLocatorInstance?.state}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: geographicalLocatorInstance, field: 'zipcode', 'error')} required">
	<label for="zipcode">
		<g:message code="geographicalLocator.zipcode.label" default="Zipcode" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="zipcode" required="" value="${geographicalLocatorInstance?.zipcode}"/>

</div>

grails-app/views/geographicalLocator/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'geographicalLocator.label', default: 'GeographicalLocator')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-geographicalLocator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-geographicalLocator" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${geographicalLocatorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${geographicalLocatorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:geographicalLocatorInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/geographicalLocator/edit.gsp
<%@ page import="commissions.GeographicalLocator" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'geographicalLocator.label', default: 'GeographicalLocator')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-geographicalLocator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-geographicalLocator" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${geographicalLocatorInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${geographicalLocatorInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:geographicalLocatorInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${geographicalLocatorInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/geographicalLocator/index.gsp
<%@ page import="commissions.GeographicalLocator" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'geographicalLocator.label', default: 'GeographicalLocator')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-geographicalLocator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-geographicalLocator" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="country" title="${message(code: 'geographicalLocator.country.label', default: 'Country')}" />
					
						<g:sortableColumn property="city" title="${message(code: 'geographicalLocator.city.label', default: 'City')}" />
					
						<g:sortableColumn property="county" title="${message(code: 'geographicalLocator.county.label', default: 'County')}" />
					
						<g:sortableColumn property="line1" title="${message(code: 'geographicalLocator.line1.label', default: 'Line1')}" />
					
						<g:sortableColumn property="line2" title="${message(code: 'geographicalLocator.line2.label', default: 'Line2')}" />
					
						<th><g:message code="geographicalLocator.party.label" default="Party" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${geographicalLocatorInstanceList}" status="i" var="geographicalLocatorInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${geographicalLocatorInstance.id}">${fieldValue(bean: geographicalLocatorInstance, field: "country")}</g:link></td>
					
						<td>${fieldValue(bean: geographicalLocatorInstance, field: "city")}</td>
					
						<td>${fieldValue(bean: geographicalLocatorInstance, field: "county")}</td>
					
						<td>${fieldValue(bean: geographicalLocatorInstance, field: "line1")}</td>
					
						<td>${fieldValue(bean: geographicalLocatorInstance, field: "line2")}</td>
					
						<td>${fieldValue(bean: geographicalLocatorInstance, field: "party")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${geographicalLocatorInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/geographicalLocator/show.gsp
<%@ page import="commissions.GeographicalLocator" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'geographicalLocator.label', default: 'GeographicalLocator')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-geographicalLocator" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-geographicalLocator" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list geographicalLocator">
			
				<g:if test="${geographicalLocatorInstance?.country}">
				<li class="fieldcontain">
					<span id="country-label" class="property-label"><g:message code="geographicalLocator.country.label" default="Country" /></span>
					
						<span class="property-value" aria-labelledby="country-label"><g:fieldValue bean="${geographicalLocatorInstance}" field="country"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${geographicalLocatorInstance?.city}">
				<li class="fieldcontain">
					<span id="city-label" class="property-label"><g:message code="geographicalLocator.city.label" default="City" /></span>
					
						<span class="property-value" aria-labelledby="city-label"><g:fieldValue bean="${geographicalLocatorInstance}" field="city"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${geographicalLocatorInstance?.county}">
				<li class="fieldcontain">
					<span id="county-label" class="property-label"><g:message code="geographicalLocator.county.label" default="County" /></span>
					
						<span class="property-value" aria-labelledby="county-label"><g:fieldValue bean="${geographicalLocatorInstance}" field="county"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${geographicalLocatorInstance?.line1}">
				<li class="fieldcontain">
					<span id="line1-label" class="property-label"><g:message code="geographicalLocator.line1.label" default="Line1" /></span>
					
						<span class="property-value" aria-labelledby="line1-label"><g:fieldValue bean="${geographicalLocatorInstance}" field="line1"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${geographicalLocatorInstance?.line2}">
				<li class="fieldcontain">
					<span id="line2-label" class="property-label"><g:message code="geographicalLocator.line2.label" default="Line2" /></span>
					
						<span class="property-value" aria-labelledby="line2-label"><g:fieldValue bean="${geographicalLocatorInstance}" field="line2"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${geographicalLocatorInstance?.party}">
				<li class="fieldcontain">
					<span id="party-label" class="property-label"><g:message code="geographicalLocator.party.label" default="Party" /></span>
					
						<span class="property-value" aria-labelledby="party-label"><g:link controller="party" action="show" id="${geographicalLocatorInstance?.party?.id}">${geographicalLocatorInstance?.party?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${geographicalLocatorInstance?.state}">
				<li class="fieldcontain">
					<span id="state-label" class="property-label"><g:message code="geographicalLocator.state.label" default="State" /></span>
					
						<span class="property-value" aria-labelledby="state-label"><g:fieldValue bean="${geographicalLocatorInstance}" field="state"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${geographicalLocatorInstance?.zipcode}">
				<li class="fieldcontain">
					<span id="zipcode-label" class="property-label"><g:message code="geographicalLocator.zipcode.label" default="Zipcode" /></span>
					
						<span class="property-value" aria-labelledby="zipcode-label"><g:fieldValue bean="${geographicalLocatorInstance}" field="zipcode"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:geographicalLocatorInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${geographicalLocatorInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>